<a href="https://colab.research.google.com/github/junseokkim93/TensorFlow-and-Deep-Learning/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is covered:

1. Introduction to tensors
1. Getting informations from tensors
1. Manipulating tensors
1. Tensors & NumPy
1. using @tf.function (a way to speed up regular Python functions
1. Using GPUs with TensorFlow(or TPUs)
1. Exercises to try for yourself!

### Markdown practice
* ctrl + M + M *to convert it to markdown cell*
* ctrl + M + Y *to convert it to code cell*
* shift + Enter *to proceed to next cell*

To see the keyboard shortcuts **ctrl + M + H**


### Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [3]:
# Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [12]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [7.,10.]],dtype=tf.float16) # specify the data type with dtype parameter
another_matrix.dtype        

tf.float16

In [15]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                     [[7,8,9],
                      [10,11,12]]])
tensor.ndim

3

### Creating tensors with 'tf.Variable'

In [19]:
# Create a tensor with tf.Variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [28]:
# Let's try change one of the element in our changeable tensor
changeable_tensor[0]=7
changeable_tensor


TypeError: ignored

In [31]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [32]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

**Note**: Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.


### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [51]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of element in a tensor

In [64]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does not affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# print(not_shuffled.ndim)
shuffled = tf.random.shuffle(not_shuffled, seed=43)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [74]:
tf.random.set_seed(50)
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

**Note**: Notice how setting the seed number *within the operation* does not make sure that you get the same array from pseudo-random setup, however `tf.random.set_seed()` does

🔥**Exercise**: Read through TensorFlow documentation on random seed genration:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.


