<a href="https://colab.research.google.com/github/junseokkim93/TensorFlow-and-Deep-Learning/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is covered:

1. Introduction to tensors
1. Getting informations from tensors
1. Manipulating tensors
1. Tensors & NumPy
1. using @tf.function (a way to speed up regular Python functions
1. Using GPUs with TensorFlow(or TPUs)
1. Exercises to try for yourself!

### Markdown practice
* ctrl + M + M *to convert it to markdown cell*
* ctrl + M + Y *to convert it to code cell*
* shift + Enter *to proceed to next cell*

To see the keyboard shortcuts **ctrl + M + H**


### Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [7.,10.]],dtype=tf.float16) # specify the data type with dtype parameter
another_matrix.dtype        

tf.float16

In [ ]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                     [[7,8,9],
                      [10,11,12]]])
tensor.ndim

3

### Creating tensors with 'tf.Variable'

In [ ]:
# Create a tensor with tf.Variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the element in our changeable tensor
changeable_tensor[0]=7
changeable_tensor


TypeError: ignored

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

**Note**: Rarely in practice will you need to decide whether to use `tf.constant` or `tf.Variable` to create tensors, as TensorFlow does this for you. However, if in doubt, use `tf.constant` and change it later if needed.


### Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers.

In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of element in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order does not affect learning)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
# print(not_shuffled.ndim)
shuffled = tf.random.shuffle(not_shuffled, seed=43)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
# tf.random.set_seed(50)
shuffled = tf.random.shuffle(not_shuffled, seed=43)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

**Note**: Notice how setting the seed number *within the operation* does not make sure that you get the same array from pseudo-random setup, however `tf.random.set_seed()` does

🔥** **Exercise**: Read through TensorFlow documentation on random seed genratiitalicized texton:
https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.




In [ ]:
tf.random.set_seed(43) # global level random seed

a = tf.random.normal(shape=(2,3), seed=10) # operation level random seed
b = tf.random.normal(shape=(2,3), seed=10)
c = tf.random.normal(shape=(2,3), seed=10)

tensors = list((a,b,c))
for idx,tensor in enumerate(tensors):
  print(idx,"-th :",tensor)
  # print("shuffled: ",tf.random.shuffle(tensor, seed= 43))
  print()




0 -th : tf.Tensor(
[[ 1.713449    1.1406013   0.29650575]
 [ 1.9050863  -0.23265524  0.07789978]], shape=(2, 3), dtype=float32)

1 -th : tf.Tensor(
[[-1.5939935  -0.5557978  -1.1867678 ]
 [ 0.21661316 -0.21811824 -0.92501515]], shape=(2, 3), dtype=float32)

2 -th : tf.Tensor(
[[ 0.36402246 -0.5901502  -0.04883237]
 [-1.821537   -0.38675845  0.38722852]], shape=(2, 3), dtype=float32)



It looks like if we want the reproducibility of tensor or shuffling of tensor, we need to use both global and operational level random seed:
>Rule 4 :If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

### Other was to make tensors

In [ ]:
# Create a tensor of all ones
tf.ones(shape = (10,7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing).

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
A = tf.constant(value=numpy_A)
A, tf.Variable(numpy_A)

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(24,) dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
B = tf.constant(numpy_A, shape = (2,12))
print(B)
tf.reshape(A,(2,3,4))

tf.Tensor(
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]], shape=(2, 12), dtype=int32)


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting information from tensors

* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors
Tensors can be indexed just like Python list

In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Add in extra dimension to rank 2 tensor
rank_2_tensor = tf.constant([[10,7],[1,2]])
rank_3_tensor = rank_2_tensor[ ...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

In [ ]:
import numpy as np
a = np.array([[1,2],[2,3]])
a[...,None], a[:,:,np.newaxis]


(array([[[1],
         [2]],
 
        [[2],
         [3]]]), array([[[1],
         [2]],
 
        [[2],
         [3]]]))

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis
# tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 1],
        [ 2]]], dtype=int32)>

### Manipulating tensors (tensor operation)

**Basic operations**

`+`,`-`,`*`,`/`

In [ ]:
# You can ad values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Substraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too
# tf.math.multiply(tensor,10)
tf.multiply(tensor,10) # alias for tf.math.multiply()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Note**:

It is smarter (Faster operation for GPU) to use `tf.` operations rather than performing raw operation such as `+`,`*` etc`

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations

In [ ]:
# Matrix multiplication in tensorflow
# tf.linalg.matmul()
tf.matmul(tensor,tensor) # alias for tf.linalg.matmul()

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

### Transpose
It is different to transpose the matrix and reshape it.

In [ ]:
mat = tf.constant([[1,2,3],[4,5,6]])
print(tf.reshape(mat,[3,2]))
mat_tp = tf.transpose(mat)
print(mat_tp)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


### The dot product
Matrix multiplication is also referred to as the dot product.
You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
print(tf.matmul(mat,mat_tp))
print(tf.tensordot(mat,mat_tp,axes=1))

tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[14 32]
 [32 77]], shape=(2, 2), dtype=int32)


### Changing the datatype of the tensor


In [ ]:
tf.__version__

'2.4.1'

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
B = tf.cast(B, dtype=tf.float16)
B.dtype

tf.float16

 ### Aggregating tensors
 Aggregating tensors = condensing them from multiple valus down to a smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

### Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of a tensor

In [ ]:
# Get the minimum value of the tensor
tensor = tf.constant([[1,2,3,4],[5,6,7,-8]])
tf.reduce_min(tensor,axis=1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, -8], dtype=int32)>

In [ ]:
# Get the maximum value of the tensor
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Get the mean of tensor
tf.reduce_mean(tensor, axis=0)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 3,  4,  5, -2], dtype=int32)>

In [ ]:
# Get the sum of a tensor
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=20>

🔥 **Exercise**: With what we've just learned, find the variance and standard deviation of our `E` tensor using TensorFlow methods.





In [ ]:
# Find the variance of our tensor
import tensorflow_probability as tfp 
E = tf.constant(value = np.random.randint(0, 100, size=100, dtype=np.int32))
tfp.stats.variance(E), tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int32, numpy=895>,
 <tf.Tensor: shape=(), dtype=float32, numpy=895.22>)

In [ ]:
# Find the standard deviation of our tensor
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.920227>

### Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional maximum and minimum 
tf.random.set_seed(90)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.23274255, 0.2738055 , 0.9907166 , 0.08686507, 0.3845886 ,
       0.02179575, 0.6601074 , 0.1190275 , 0.46137857, 0.7338376 ,
       0.6237539 , 0.55857694, 0.0852828 , 0.00776148, 0.28429675,
       0.00864708, 0.77577007, 0.63237107, 0.8463516 , 0.48504388,
       0.6638707 , 0.20488667, 0.47555852, 0.06405985, 0.68311787,
       0.76344955, 0.39875257, 0.43225622, 0.31935418, 0.00655234,
       0.72540605, 0.52421427, 0.25992632, 0.6519724 , 0.21613872,
       0.927868  , 0.5286405 , 0.7603172 , 0.19602346, 0.09403837,
       0.00396311, 0.5251659 , 0.5154805 , 0.8766421 , 0.39734387,
       0.6982125 , 0.7360716 , 0.92651224, 0.9999789 , 0.18750894],
      dtype=float32)>

In [ ]:
# Find the positional maximum and minimum
assert F[tf.argmax(F)] == tf.reduce_max(F)


In [ ]:
# Find the positional minimum
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.003963113>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G) # removes the dimensions of size 1 from the tensor
G_squeezed.shape

TensorShape([50])

### One-hot encoding tensors

In [ ]:
# Create one-hot encoding from indices list
idx_list = [0, -31, 23, 30]
tf.one_hot(idx_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(idx_list, depth=8, on_value="T", off_value="F")

<tf.Tensor: shape=(4, 8), dtype=string, numpy=
array([[b'T', b'F', b'F', b'F', b'F', b'F', b'F', b'F'],
       [b'F', b'F', b'F', b'F', b'F', b'F', b'F', b'F'],
       [b'F', b'F', b'F', b'F', b'F', b'F', b'F', b'F'],
       [b'F', b'F', b'F', b'F', b'F', b'F', b'F', b'F']], dtype=object)>

### Squaring, log, square root

In [3]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [4]:
# Square it
tf.math.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [6]:
# Find the squareroot
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [9]:
# Find the log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

TensorFlow interacts beautifully with NumPy arrays.

In [13]:
# Create a tensor directly from a NumPy arrays
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

In [22]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)